# Generated by Django 2.2 on 2019-07-08 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0003_auto_20190708_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='target_ct',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(('app_label', 'images'), ('model', 'image')), models.Q(('app_label', 'auth'), ('model', 'user')), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_obj', to='contenttypes.ContentType'),
        ),
    ]
