# Generated by Django 2.1.7 on 2019-04-12 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_number', models.IntegerField()),
                ('cols_number', models.IntegerField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CutPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_field', models.ImageField(unique=True, upload_to='cut_collage_photos')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_url', models.URLField(default='tutorial:index')),
                ('img_field', models.ImageField(unique=True, upload_to='upload_collage_photos')),
                ('valid', models.BooleanField(default=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhotoSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(default=128, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='cutphoto',
            name='photo_src',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collage.Photo'),
        ),
        migrations.AddField(
            model_name='collage',
            name='photo_size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collage.PhotoSize'),
        ),
        migrations.AddField(
            model_name='collage',
            name='photos',
            field=models.ManyToManyField(blank=True, to='collage.Photo'),
        ),
    ]
