# Generated by Django 2.2 on 2019-06-26 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CutPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_field', models.ImageField(upload_to='cut_collage_photos')),
                ('img_location', models.FilePathField(path='D:\\opencv\\heroku\\heroku\\media\\upload_async')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('photo_type', models.IntegerField(choices=[(0, 'Objs rounded with rect'), (128, 'Resized to 128'), (256, 'Resized to 256'), (1, 'cut')], default=1)),
                ('size', models.IntegerField(default=128)),
            ],
        ),
        migrations.CreateModel(
            name='PhotoSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(default=128)),
            ],
        ),
        migrations.CreateModel(
            name='ProgressRecorder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('percent', models.IntegerField(default=0)),
                ('proc_name', models.CharField(default='downloading', max_length=30)),
                ('collage_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_url', models.URLField(default='tutorial:index')),
                ('img_field', models.ImageField(blank=True, upload_to='upload_collage_photos')),
                ('img_location', models.FilePathField(path='D:\\opencv\\heroku\\heroku\\media\\upload_async')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('cut_photos', models.ManyToManyField(blank=True, related_name='photos', to='collage.CutPhoto')),
            ],
        ),
        migrations.CreateModel(
            name='Collage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_number', models.IntegerField(default=10)),
                ('cols_number', models.IntegerField(default=5)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('photo_tag', models.CharField(default='women', max_length=30)),
                ('photo_size', models.IntegerField(choices=[(128, '128'), (256, '256'), (512, '512')], default=128)),
                ('final_img', models.ImageField(blank=True, upload_to='collages')),
                ('photos', models.ManyToManyField(blank=True, related_name='collages', to='collage.Photo')),
            ],
            options={
                'ordering': ('-create_date',),
            },
        ),
    ]
