# Generated by Django 2.1.7 on 2019-04-12 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collage', '0002_auto_20190412_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collage',
            name='photo_size',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='PhotoSize',
        ),
    ]
