# Generated by Django 2.2.3 on 2019-07-17 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collage', '0002_auto_20190708_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cutphoto',
            name='img_location',
            field=models.FilePathField(path='D:\\opencv\\heroku\\heroku\\media\\upload_async'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='img_location',
            field=models.FilePathField(path='D:\\opencv\\heroku\\heroku\\media\\upload_async'),
        ),
    ]
