# Generated by Django 2.2 on 2019-06-24 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collage', '0003_cutphoto_photo_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cutphoto',
            name='size',
            field=models.IntegerField(default=128),
        ),
        migrations.AlterField(
            model_name='collage',
            name='photos',
            field=models.ManyToManyField(blank=True, related_name='collages', to='collage.Photo'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='cut_photos',
            field=models.ManyToManyField(blank=True, related_name='photos', to='collage.CutPhoto'),
        ),
    ]
