# Generated by Django 2.1.7 on 2019-04-14 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collage', '0005_auto_20190414_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='collage',
            name='final_img',
            field=models.ImageField(default=1, upload_to='collages'),
            preserve_default=False,
        ),
    ]
