# Generated by Django 2.2.2 on 2019-06-07 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collage', '0007_auto_20190605_1012'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_number', models.IntegerField(default=10)),
                ('cols_number', models.IntegerField(default=5)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('photo_tag', models.CharField(default='women', max_length=30)),
                ('photo_size', models.IntegerField(choices=[('128', 128), ('256', 256)], default=128)),
                ('final_img', models.ImageField(blank=True, upload_to='collages')),
            ],
            options={
                'ordering': ('-create_date',),
            },
        ),
    ]
