# Generated by Django 2.2.2 on 2019-06-09 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collage', '0008_collage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collage',
            name='photo_size',
            field=models.IntegerField(choices=[(128, '128'), (256, '256')], default=128),
        ),
    ]
